sudo: required
language: node_js
node_js:
  - '10'
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: npm run test:ci
env:
  - NODE_VERSION=10 NODE_ENV=test REDIS_URL=redis://redis@localhost:6379/0 DATABASE_URL=postgres://postgres@localhost/travis_ci_test ALPHA_VANTAGE_API_KEY=foo TZ=GMT
