version: '3'
services:
  db:
    image: postgres:10.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:10.2
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '127.0.0.1:7432:5432'
    volumes:
      - pgtestdata:/var/lib/postgresql/test-data

  redis:
    image: redis:3.2
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redisdata:/var/lib/redis/data

  test-redis:
    image: redis:3.2
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - redistestdata:/var/lib/redis/data

volumes:
  pgdata: {}
  pgtestdata: {}
  redisdata: {}
  redistestdata: {}
